# Generated by Django 5.2 on 2025-04-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='punch_photos/in/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_photo',
            field=models.ImageField(blank=True, null=True, upload_to='punch_photos/out/'),
        ),
    ]
