# Generated by Django 5.2 on 2025-04-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_punch_in_photo_attendance_punch_out_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in_photo',
            field=models.ImageField(upload_to='punch_photos/in/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out_photo',
            field=models.ImageField(upload_to='punch_photos/out/'),
        ),
    ]
