# Generated by Django 5.2 on 2025-04-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='punch_photos/in/'),
        ),
    ]
