# Generated by Django 5.2 on 2025-04-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_leaverequest_date_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_in_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='pending', max_length=10),
        ),
    ]
