# Generated by Django 5.2 on 2025-04-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_raw_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='raw_password',
        ),
    ]
